//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace task425_7_2024.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class product
    {
        public int productID { get; set; }
        public string productName { get; set; }
        public string productdescription { get; set; }
        public string productQuantity { get; set; }
        public Nullable<int> productPrice { get; set; }
    }
}
